CNProject/Models/AppDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CNProject.Models
{
    public class AppDbContext : IdentityDbContext<AppUser>
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
           : base(options) { }

        public DbSet<AppUser> AppUsers { get; set; }
    }

}

CNProject/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CNProject.Models
{
    public class AppUser : IdentityUser
    {

        public AppUser() : base() { }
    }
}

CNProject/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CNProject.ViewModels
{
    public class UserViewModel
    {
        public string Email { get; set; }
        public string Name { get; set; }
        public string password { get; set; }
    }
}

CNProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CNProject.Controllers
{
    public class HomeController : Controller
    {
        [Route("")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        [Route("[controller]/[action]")]
        public IActionResult Welcome()
        {
            return View();
        }

    }
}

CNProject/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CNProject.Models;
using CNProject.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CNProject.Controllers
{

    [Route("[controller]/[action]")]
    public class RegisterController : Controller
    {
        public UserManager<AppUser> userManager;
        private SignInManager<AppUser> sgnMgr;

        public RegisterController(UserManager<AppUser> userMgr, SignInManager<AppUser> signInManager)
        {
            userManager = userMgr;
            sgnMgr  = signInManager;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RegisterActionAsync(UserViewModel viewModel)

        {
            AppUser user = new AppUser();
            user.Email = viewModel.Email;
            user.UserName = viewModel.Name;
            await userManager.CreateAsync(user, viewModel.password);
            return Redirect("/");
        }

        public IActionResult Login() => View();

        public async Task<IActionResult> LoginActionAsync(UserViewModel viewModel)
        {
            AppUser user = await userManager.FindByEmailAsync(viewModel.Email);
            if ((await sgnMgr.PasswordSignInAsync(user, viewModel.password, false, false)).Succeeded)
            {
                return Redirect( "/Home/Welcome");
            }
            return Redirect("/");
        }
    }
}

CNProject/Views/Home/Index.cshtml
    <a href="@Url.Action("Login","Register")">Login</a>
    <br />
    <a href="@Url.Action("Index","Register")">Register</a>
    <br />
    <a href="@Url.Action("Welcome","Home")">Welcome Page</a>

CNProject/Views/Home/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

CNProject/Views/Register/Index.cshtml
@model UserViewModel

<form asp-action="RegisterActionAsync" asp-controller="Register" method="post">
    <div>
        <label asp-for="Name">User Name</label>
        <input type="text" class="form-control" placeholder="Enter your name"
               asp-for="Name" />
    </div>
    <div>
        <label asp-for="Email">Email:</label>
        <input type="text" class="form-control" placeholder="Enter your email"
               asp-for="Email" />
    </div><div>
        <label asp-for="password">Password:</label>
        <input type="password" class="form-control" placeholder="Enter your password"
               asp-for="password" />
    </div>

    <button type="submit" >Register</button>

</form>

CNProject/Views/Register/Login.cshtml
@model UserViewModel

<form asp-action="LoginActionAsync" asp-controller="Register" method="post">

    <div>
        <label asp-for="Email">Email:</label>
        <input type="text" class="form-control" placeholder="Enter your email"
               asp-for="Email" />
    </div><div>
        <label asp-for="password">Password:</label>
        <input type="password" class="form-control" placeholder="Enter your password"
               asp-for="password" />
    </div>

    <button type="submit" >Login</button>
</form>

CNProject/Views/Shared/_Layouts.cshtml
<html>
<head></head>
<body>
    @RenderBody()
</body>
</html>